name: CI Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK pour Maven
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11' # Changez la version si nécessaire

      # Build du projet avec Maven pour générer le fichier WAR
      - name: Build with Maven
        run: mvn clean package

      # Vérifie la présence du fichier WAR
      - name: Verify WAR file
        run: |
          echo "Listing files in target directory:"
          ls -l target/
          echo "Checking if WAR file exists"
          if [ ! -f "target/TP_A18_ci_cd_SOUMATIA-1.0-SNAPSHOT.war" ]; then
            echo "WAR file not found!"
            exit 1
          fi

      # Connexion à Docker Hub
      - name: Log in to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          echo "Logging into Docker Hub..."
          echo "${DOCKER_HUB_TOKEN}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin
          if [ $? -ne 0 ]; then
            echo "Docker login failed!"
            exit 1
          fi

      # Build de l'image Docker
      - name: Build Docker image
        run: docker build --no-cache --progress=plain -t ${{ secrets.DOCKER_HUB_USERNAME }}/tp_a18_ci_cd_soumatia:latest .

      # Push de l'image vers Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/tp_a18_ci_cd_soumatia:latest

      # Nettoyage de l'image locale
      - name: Remove local Docker image
        run: docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/tp_a18_ci_cd_soumatia:latest || true
